openapi: 3.0.0
info:
  title: Joke Submission API
  version: 1.0.0
servers:
  - url: https://mushy-ocean-43.webhook.cool
paths:
  /submit_joke:
    post:
      summary: Submit a new joke
      operationId: submitJoke
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                question:
                  type: string
                  example: Why don't scientists trust atoms?
                answer:
                  type: string
                  example: Because they make up everything!
              required:
                - question
                - answer
      responses:
        '200':
          description: Joke submitted successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Joke received successfully.
