openapi: 3.0.0
info:
  title: PII Classification Submission API
  version: 1.1.0
  description: API for submitting PII classification data to webhook endpoint.

paths:
  /api/discovery-platform/v1/scan-data:
    post:
      summary: Submit scan data for PII classification
      operationId: scanData
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ClassificationRecord"
            example:
              AssetPath: "mssql://sample.database.windows.net/CustomerDB/dbo/CustomerFlights14"
              Classification:
                - "MICROSOFT.PERSONAL.EMAIL"
              ClassificationDetails:
                - Name: "MICROSOFT.PERSONAL.EMAIL"
                  Confidence: 86
                  Count: 1
                  UniqueCount: 1
              TimeGenerated: "2025-09-02T19:10:09.302577Z"
              Id: "2ea339274edbb31b242eb19e284f58bc77ab52dd9fa870e123fe1108b1efbdfe"
              ExternalID: "mssql://sample.database.windows.net/CustomerDB/dbo/CustomerFlights14"
              SourceName: "AzureSqlDatabase-Crl"
              SourceType: "Azure SQL Server"
              SourceRegion: "United States"
              AssetName: "CustomerFlights14"
              AssetType: "Table"
              ItOwner: "na@notavailable.com"
      responses:
        "200":
          description: Successfully submitted
        "400":
          description: Invalid payload
        "500":
          description: Server error

components:
  schemas:
    ClassificationDetail:
      type: object
      properties:
        Name:
          type: string
          description: Classification label
        Confidence:
          type: integer
          description: Confidence percentage (0-100)
        Count:
          type: integer
          description: Number of matches
        UniqueCount:
          type: integer
          description: Number of unique matches
      required:
        - Name
        - Confidence
        - Count
        - UniqueCount

    ClassificationRecord:
      type: object
      properties:
        AssetPath:
          type: string
        Classification:
          type: array
          items:
            type: string
        ClassificationDetails:
          type: array
          items:
            $ref: "#/components/schemas/ClassificationDetail"
        TimeGenerated:
          type: string
          format: date-time
        Id:
          type: string
          description: Unique identifier (hash or GUID)
        ExternalID:
          type: string
        SourceName:
          type: string
        SourceType:
          type: string
        SourceRegion:
          type: string
        AssetName:
          type: string
        AssetType:
          type: string
        ItOwner:
          type: string
          format: email
      required:
        - AssetPath
        - Classification
        - ClassificationDetails
        - TimeGenerated
        - ExternalID
        - SourceName
        - SourceType
        - SourceRegion
        - AssetName
        - AssetType
