openapi: 3.0.0
info:
  title: OneTrust Integration Manager API
  description: API to send privacy breach incident alerts to OneTrust
  version: 1.0.0

paths:
  /integrationmanager/api/v1/webhook/f10eb14d-9545-4645-9de7-1f3c0d83c821:
    post:
      summary: Send Privacy Breach Incident Alert to OneTrust
      description: Sends an incident alert with details, including jurisdictions.
      operationId: sendPrivacyBreachIncidentAlertToOneTrust
      requestBody:
        description: A JSON object containing details of the privacy breach, including the name, description, and an array of affected jurisdictions.
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: Name of the incident or alert.
                  example: "Data Leak Alert"
                description:
                  type: string
                  description: Detailed description of the privacy breach.
                  example: "Sensitive customer data was exposed due to a system misconfiguration."
                jurisdictions:
                  type: array
                  items:
                    type: string
                  description: List of affected jurisdictions (must be an array of strings).
                  example: ["France", "United Kingdom"]
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Webhook processed successfully"
        '400':
          description: Bad request - Invalid input parameters
        '500':
          description: Internal server error
