openapi: 3.0.0
info:
  title: OneTrust Integration Manager API
  description: API to send privacy breach incident alerts to OneTrust
  version: 1.0.0

paths:
  /integrationmanager/api/v1/webhook/f10eb14d-9545-4645-9de7-1f3c0d83c821:
    post:
      summary: Send Privacy Breach Incident Alert to OneTrust
      description: Sends an incident alert with details, including jurisdictions, to OneTrust.
      operationId: sendPrivacyBreachIncidentAlertToOneTrust
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: Name of the incident or alert
                  example: "test"
                description:
                  type: string
                  description: Description of the privacy breach
                  example: "test"
                jurisdictions:
                  type: array
                  description: List of affected jurisdictions
                  items:
                    type: string
                  example: ["France"]
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Webhook processed successfully"
        '400':
          description: Bad request - Invalid input parameters
        '500':
          description: Internal server error
